### ISSUE TITLE
Demo

### ISSUE THREAD

**Issue by LAW1223** [custom-humans/editable-humans#1]
Thank you for your excellent research.  After I runned the demo code, the result is mesh without color. Have I missed something to do?

**Comment by custom-humans** [comment]
Thanks for your interest in our work. 

We use vertex colors in the output obj file. You can quickly check if there are 6 columns by opening the obj file with a text editor. Like this:

<img width="488" alt="Screen Shot 2023-07-16 at 4 39 58 PM" src="https://github.com/custom-humans/editable-humans/assets/126664174/d0a07e77-4082-4c7f-9682-a1c96ab011e2">

You also need to make sure your mesh visualization tools support vertex colors. I was able to visualize it with Mac QuickLook preview, MeshLab, and [aitviewer](https://github.com/eth-ait/aitviewer).

Please let me know if you found that vertex colors are not included in the obj file. Thanks!
