### ISSUE TITLE
Cross-subjects feature editing

### ISSUE THREAD

**Issue by 12awei** [custom-humans/editable-humans#10]
I tried your Clothing Transfer module and it seems like he chose the whole body.
How to achieve the option of choosing between the upper or lower body as mentioned in your paper?
![image](https://github.com/user-attachments/assets/19462522-3d86-49c8-ac7c-3a2b36399435)

**Comment by custom-humans** [comment]
Hi,

Under this line https://github.com/custom-humans/editable-humans/blob/main/demo.py#L58
we can provide the mesh index we want to edit. For example I have provided lower body indices in the json file. 

What you need to do is to select vertex indices of the "SMPL-X" mesh you want to edit. 

Currently there is no automatic way to do so. I would suggest you use Blender to select a group of region and print our the vertex IDs.

**Comment by 12awei** [comment]
After using the Clothing Transfer module, the obtained. obj file does not have a material file. How can I convert this file into an. obj file with a material file for easier animation operations in the future. Perhaps it can be achieved in Blender, how can I do it specifically

**Comment by azuxmioy** [comment]
Hi,
You can check how we did UV unwrapping with `xatlas` in another repo:

https://github.com/SiTH-Diffusion/SiTH/blob/main/recon/models/evaluator.py#L145
