### ISSUE TITLE
Animation Process

### ISSUE THREAD

**Issue by Moronrift08** [custom-humans/editable-humans#11]
Hi, thanks for your excellent work!

It seems that you don't use learning-based methods for animation because there is no GT smpl available.
So I am wondering how you make such a good animation results.
In the code,  it takes the target smpl to reconstruct the mesh and uses the texture codebook learned from the training process for reconstruction.  The 'repose' function just use the target smpl and then add texture to it. Hence, you treat the animation like the reconstruction process. Am I right or there are some misundrstandings?

**Comment by azuxmioy** [comment]
Yes, you are correct.

The method does not learn deformation or skinning weights, so it does not tackle pose-dependent deformation.

This strategy is closer to using nearest neighbors on a SMPL-X body model. It's easy to generalize but also has shortcomings near the underarm areas or close contact.

**Comment by Moronrift08** [comment]
Thanks a lot for your reply!
