### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by muses0229** [custom-humans/editable-humans#5]

**Comment by custom-humans** [comment]
Hi I tried to install it again on my PC and it still works.

From your error message, it seems that it's a network or firewall issue?

Can you try to git clone their github repo and try to build it locally? I guess the version doesn't matter here.

![Screen Shot 2023-10-26 at 12 01 06 PM](https://github.com/custom-humans/editable-humans/assets/126664174/2d4ff33c-3e55-4808-84d1-d4e6d4712808)
