### ISSUE TITLE
Change into new clothes

### ISSUE THREAD

**Issue by 12awei** [custom-humans/editable-humans#8]
Hello author. Do I have to provide a 3D model of the person wearing the new clothes if I want to change the 3D human body into new clothes? Can providing only pictures of new clothes complete the task? Please give me some advice.

**Comment by azuxmioy** [comment]
Hi. This project only supports 3D editing given 3D meshes.
To achieve your task, I'd suggest you try 2D virtual try-on and 2D-to-3D reconstruction.
