### ISSUE TITLE
Inquiry about two files in the project

### ISSUE THREAD

**Issue by Moronrift08** [custom-humans/editable-humans#9]
Excuse me, What are the functions of the two files smpl_mesh.pkl and thuman_smpl_mesh.pkl in editable-humans/data/ ?
? 
I tried to use 200 data in costumhumans dataset to train the model
And running evaluation reports that the file smpl_mesh.pkl limits the dim of 100.

**Comment by azuxmioy** [comment]
Hi, that's just a file we store all the registered SMPL-X meshes.

there are two items inside, 'smpl_F' and 'smpl_V', faces and vertices.

For 'smpl_F', you can just reuse it. For 'smpl_V', you will need to replace it with your 200 training samples.

Your shape of the torch tensor 'smpl_V' should be [200, 10475, 3]

**Comment by Moronrift08** [comment]
Got it. Many thanks for your reply!
